# Generated by Django 2.2.7 on 2019-12-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(blank=True, help_text='other actions of squirrel besides running, chasing, climbing, eating and foraging', max_length=1000),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(blank=True, help_text='specific location of squirrel', max_length=1000),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='squirrel_id',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=1000, unique=True),
        ),
    ]
